game関連のAPIのhandler実装
traPtitech/trap-collection-server pull request #456
Opened 2022-10-12 09:50 UTC by ikura-hamu

した。

2022-10-12 10:47 UTC, mazrean requested changes
全体の話ですが、internal server errorは基本的に起きてはならないエラーなので、internal server errorの場合はログに残しておいてほしいです。
また、bad requestなどの普通に起こりうるエラーはログに残すとログが荒れてしまうのでログに残さない方が良いです。
あと、これは説明しなかったのが悪いですが`failed to~`系のエラーメッセージは想定外のエラーの時(=internal server errorを返すとき)に返すようにしたいので、bad requestとかでは返さないようにして欲しいです:pray:

それ以外はほぼokです。
修正お願いします:pray;

2022-10-12 10:47 UTC, mazrean commented on src/handler/v2/game.go
> +	isAll := bool(*params.All)
クエリパラメーター`all`の指定がないとき、`params.All`がnilになってヌルポしてしまうので、nilかチェックして、nilの場合`isAll = false`にしないといけなさそう

2022-10-12 10:47 UTC, mazrean commented on src/handler/v2/game.go
> +		return echo.NewHTTPError(http.StatusBadRequest, "Internal Server Error")
エラーメッセージ直すの忘れていそう

2022-10-12 10:47 UTC, mazrean commented on src/handler/v2/game.go
> +		return echo.NewHTTPError(http.StatusBadRequest, "Internal Server Error")
ここもエラーメッセージ直すの忘れていそう

2022-10-12 10:47 UTC, mazrean commented on src/handler/v2/game_test.go
> +	testCases := []test{
request bodyがjsonでないなどの時、`c.Bind`がエラーになるので、このような時に400が変えるかのチェックが欲しいです

2022-10-12 10:47 UTC, mazrean commented on src/handler/v2/game_test.go
> +	testCases := []test{
postと同様にrequest bodyがjsonでないなどの時、`c.Bind`がエラーになるので、このような時に400が変えるかのチェックが欲しいです

2022-10-12 10:47 UTC, mazrean commented on src/handler/v2/game.go
> +	isAll := bool(*params.All)
あと、`*params.All`で既にbool型なので、型変換はしないで良いです

2022-10-12 10:47 UTC, mazrean commented on src/handler/v2/game.go
> +		limit = int(*params.Limit)
`*params.Limit`の時点で既にint型なので、型変換はしないで良いです

2022-10-12 10:47 UTC, mazrean commented on src/handler/v2/game.go
> +		offset = int(*params.Offset)
limitと同様に、型変換はしないで良いです

2022-10-12 10:47 UTC, mazrean commented on src/handler/v2/game.go
> +			return echo.NewHTTPError(http.StatusInternalServerError, "Internal Server Error")
エラーメッセージでもう少し詳しい情報(`failed to get games`ぐらい)が欲しいです

2022-10-12 10:47 UTC, mazrean commented on src/handler/v2/game.go
> +			return echo.NewHTTPError(http.StatusInternalServerError, "Internal Server Error")
ここももう少し詳しいエラーの情報が欲しいです

2022-10-12 11:16 UTC, ikura-hamu commented on src/handler/v2/game.go
> +			return echo.NewHTTPError(http.StatusInternalServerError, "Internal Server Error")
一応エラーメッセージは[swagger](https://apis.trap.jp/?urls.primaryName=traP%20Collection%20v2%20API#/game/getGames)を参考にして書いてたのですが（それでも違うところはある）、エラーの内容によって適宜エラーメッセージを変えた方がいいということですか？

2022-10-13 06:06 UTC, mazrean commented on src/handler/v2/game.go
> +			return echo.NewHTTPError(http.StatusInternalServerError, "Internal Server Error")
swaggerのexampleは500とか400とかに関わらず同じになっているので、エラーメッセージは適宜変えて欲しいです:pray:

2022-10-13 06:07 UTC, mazrean approved these changes
LGTM!

2022-10-13 07:31 UTC, merged