Game関連のAPIでSQL文を適切に修正
traPtitech/trap-collection-server pull request #458
Opened 2022-10-13 07:21 UTC by ikura-hamu

### 以前
全てのゲームを取得して、配列の長さから全ゲームの個数を、limit,offsetをかけて必要なゲームを取得していた。

### 今回
SQL文にLimitとOffsetをつけて必要なだけゲームを取得し、全ゲームの個数はCountを使って別途取得するようにした。

2022-10-13 10:06 UTC, mazrean requested changes
ほぼokです。
ただ、いくつか気になったところがあったのでそこだけ修正お願いします:pray:

2022-10-13 10:06 UTC, mazrean commented on src/repository/gorm2/v2_game.go
> +		err = db.
↓みたいにlimit,offsetで変わる部分以外は共通化できるので、分岐の中でlimit、offsetの設定だけして、`Find`とかorderの設定は分岐外でした方が良さそう
https://github.com/traPtitech/anke-to/blob/ae394bc63b3215a925038f3b6edcdbb0c6f13bd6/model/questionnaires_impl.go#L170-L243

2022-10-13 10:06 UTC, mazrean commented on src/repository/gorm2/v2_game.go
> +		err = db.
このぐらい分岐が多いとswitchでhttps://go.dev/ref/spec#Switch_statements 、Expression switchesの例の一番下みたいに書いた方がわかりやすそう(今回は分岐減りそうだけど)

2022-10-14 05:18 UTC, mazrean requested changes
いくつか気になったところがあったので修正お願いします:pray:

2022-10-14 05:18 UTC, mazrean commented on src/repository/gorm2/v2_game.go
> +		Where("deleted_at IS NULL").
`deleted_at IS NULL`、設定しなくても勝手につけてくれそうな気もする(つかなかったら無視して大丈夫です)

2022-10-14 05:18 UTC, mazrean commented on src/repository/gorm2/v2_game.go
> +		lim = -1
前のレビューで意図していたのは、
```go
query := db.
    Order("created_at DESC")

if limit > 0 {
    query = query.Limit(limit)
}

if offset > 0 {
    query = query.Offset(offset)
}

err = query.Find(&games)
```
みたいなことができる、という意味だった

2022-10-14 05:18 UTC, mazrean commented on src/repository/gorm2/v2_game.go
>  		Joins("JOIN game_management_roles ON game_management_roles.game_id = games.id").
gormの[session](https://gorm.io/ja_JP/docs/session.html#NewDB)使うとCountとjoinとかはまとめられて良さそう

2022-10-14 05:23 UTC, ikura-hamu commented on src/repository/gorm2/v2_game.go
> +		lim = -1
了解です。limitが-1なのは、これ↓で`limit -1`にするとlimitが取り消されるみたいなことが書いてあって、やってみたらテストが通ったので使いました。
https://gorm.io/ja_JP/docs/query.html#Limit-amp-Offset

2022-10-14 05:24 UTC, ikura-hamu commented on src/repository/gorm2/v2_game.go
> +		Where("deleted_at IS NULL").
これはテストのときに削除済みのものを取ってしまっていたので付けました。

2022-10-14 05:33 UTC, mazrean commented on src/repository/gorm2/v2_game.go
> +		lim = -1
なるほど。ただ、あまり特殊な仕様は使うと変なバグの原因になったりするので使いたくなさがあるのと、GORM、この辺りの細かい仕様は破壊的な変更さらっとしてきたりするので、使わない方が良い気がしているので修正でお願いします:pray:

2022-10-15 12:39 UTC, mazrean approved these changes
LGTM!

2022-10-15 13:46 UTC, merged