admin関連APIのservice実装
traPtitech/trap-collection-server pull request #497
Opened 2022-10-24 06:57 UTC by ikura-hamu

した。テストは存在しない。

2022-10-24 12:25 UTC, mazrean requested changes
いくつか気になったところがあったので修正お願いします:pray:

2022-10-24 12:25 UTC, mazrean commented on src/service/v2/admin_auth.go
> +			adminInfos = append(adminInfos, service.NewUserInfo(
既に`UserInfo`構造体の値が存在しているのに追加でさらにインスタンス作っているのが(本当に僅かだけど)メモリ的に無駄なので、`getActiveUsers`の返り値を使った方が良さそう

2022-10-24 12:25 UTC, mazrean commented on src/service/v2/admin_auth.go
> +		adminsMap := make(map[values.TraPMemberID]struct{})
ここは複数回存在確認する訳ではないので、わざわざmap作らず普通にループの中でチェックした方が良さそう。

2022-10-24 12:25 UTC, mazrean commented on src/service/v2/admin_auth.go
> +				activeUsersMap[adminID],
ユーザーが凍結されている場合、`activeUsersMap[adminID]`が存在しない可能性があるので、その場合のハンドリングが必要そう

2022-10-24 12:25 UTC, mazrean commented on src/service/v2/admin_auth.go
> +		for _, adminID := range adminIDs {
この手前に`adminInfos = make([]*service.UserInfo, 0, len(adminIDs)+1)`入れておいた方が効率良さそう。

2022-10-24 12:25 UTC, mazrean commented on src/service/v2/admin_auth.go
> +			adminsInfo = append(adminsInfo, service.NewUserInfo(
`AddAdmin`と同様に、`getActiveUsers`の結果利用した方が良さそう。

2022-10-24 12:25 UTC, mazrean commented on src/service/v2/admin_auth.go
> +			//adminが凍結されているとき、一応ログを残す。
正常に動作していても普通に起こりうる状況で、ログに残すとログが荒れて本当に重要なログがわかりづらくなるので、ここはログに残さないで良さそう。

2022-10-24 12:25 UTC, mazrean commented on src/service/v2/admin_auth.go
> +			log.Printf("not active user: %v", adminID) //ユーザーが凍結されているとき一応ログに残す
`GetAdmins`と同様に、ここはログに残さないで良さそう

2022-10-24 12:25 UTC, mazrean commented on src/service/v2/admin_auth.go
> +				service.NewUserInfo(
`AddAdmin`、`GetAdmins`と同様に、`getActiveUsers`の結果を利用した方が良さそう。

2022-10-24 12:25 UTC, mazrean commented on src/service/v2/admin_auth.go
> +func (aa *AdminAuth) AdminAuthorize(ctx context.Context, session *domain.OIDCSession) error {
(game roleの時に見逃してしまった気がするけど)sessionの有効期限が切れている可能性があるので、https://github.com/traPtitech/trap-collection-server/blob/961f5674f9b7254dd22ca03c94defcddf92bdbbd/src/service/v2/oidc.go#L77-L79 と同様にしてsessionの有効期限のチェックをしてほしい

2022-10-24 12:25 UTC, mazrean commented on src/service/v2/admin_auth.go
> +	adminsID, err := aa.adminAuthRepository.GetAdmins(ctx)
できればユーザーidを引数にして、adminの存在を確認するメソッドをrepositoryに生やした方が無駄なデータを取り出さないで良くなるので良さそう。
ただ、実装しないといけないメソッド数が増えて実装にかかる時間が増えるので、それで間に合わなくなりそう一旦放置でも良い気はする(=変更するかは任せます)。

2022-10-25 04:04 UTC, ikura-hamu commented on src/service/v2/admin_auth.go
> +	adminsID, err := aa.adminAuthRepository.GetAdmins(ctx)
時間を優先して、現状のまま進めようと思います。

2022-10-25 09:46 UTC, mazrean approved these changes
LGTM!

2022-10-25 09:57 UTC, merged