POST /games/asset/:gameID/url実装
traPtitech/trap-collection-server pull request #67
Opened 2020-10-06 12:12 UTC by mazrean

実装した。

2020-10-06 13:19 UTC, FujishigeTemma requested changes

2020-10-06 13:19 UTC, FujishigeTemma commented on model/maps.go
> +var gameTypeStrIntMap = map[string]uint8{
enumとして使ってるからassetType(s)とかのほうが自然
あと、Golangのお作法的には下みたいな書き方のほうがわかりやすいと思う
```
// AssetTypeURL ブラウザゲーム
AssetTypeURL = iota
// AssetTypeJar Jarファイル
AssetTypeJar
// AssetTypeWindowsExe Windows実行ファイル
AssetTypeWindowsExe
// AssetTypeMacApp Mac版App
AssetTypeMacApp
```

2020-10-06 13:19 UTC, FujishigeTemma commented on model/game_assets.go
> +		if err != nil {
ここも別のエラー返してあげるほうが良さ

2020-10-06 17:06 UTC, mazrean commented on model/game_assets.go
> +		if err != nil {
#64 のやつでなおるので飛ばします

2020-10-06 17:17 UTC, mazrean commented on model/maps.go
> +var gameTypeStrIntMap = map[string]uint8{
iotaを使ってしまうとDBの値との対応関係が見えづらくなるので数字を入れた変数を作った。

2020-10-07 13:19 UTC, FujishigeTemma approved these changes

2020-10-07 13:20 UTC, merged