dockertestの導入
traPtitech/trap-collection-server pull request #691
Opened 2023-09-19 10:14 UTC by ikura-hamu

resolve: #468

2023-09-21 08:57 UTC, mazrean requested changes
消えると面倒なので、とりあえず一旦今まで気になったポイントだけsubmitしておきます

2023-09-22 05:14 UTC, ikura-hamu commented on src/repository/gorm2/db_test.go
> +	if err = pool.Purge(resource); err != nil {
os.Exitがdeferを実行しないのでこうなっています。

2023-09-24 14:53 UTC, mazrean commented on src/repository/gorm2/db_test.go
> +	if err = pool.Purge(resource); err != nil {
あー、それがあったか。それならこれで良さそう(無名関数でもう一段囲うとかも手としてはあるけど、可読性が下がるのでしないで良さそう)。

2023-09-25 05:25 UTC, mazrean approved these changes
LGTM!
ただ、1点だけ少し綺麗に書けそうな箇所があったのでコメント入れました。

2023-09-25 05:25 UTC, mazrean commented on src/config/v1/storage.go
> +	return s3UsePathStyle == "true"
`os.LookupEnv`使った方が「デフォルトは`false`」というのが分かりやすくてよいかも。
あと、`bool`のstringの判定は`strconv.ParseBool`とかを使った方が綺麗にできて良さそう。

2023-09-25 05:28 UTC, ras0q commented on src/repository/gorm2/db_test.go
> +	if err = pool.Purge(resource); err != nil {
部外者なんですが、1.15からox.exit呼ばなくてよくなってるのでdeferでやっちゃってよさそうです:eyes:
https://go.dev/doc/go1.15#testing

2023-09-30 04:51 UTC, merged