POST /versions/:launcherVersionID/game実装
traPtitech/trap-collection-server pull request #71
Opened 2020-10-08 11:35 UTC by mazrean

実装した。
stringの配列そのままだとリクエストのbindがうまく出来ないのでopenapiを少し書き換えた。

2020-10-08 12:33 UTC, mazrean commented
ゲームが存在するかのチェックがされていないので一旦ドラフトにした

2020-11-25 10:38 UTC, FujishigeTemma commented
CI落ちてるよ

2020-12-02 08:49 UTC, mazrean commented
CI通った

2020-12-02 18:52 UTC, FujishigeTemma requested changes

2020-12-02 18:52 UTC, FujishigeTemma commented on model/game_version_relations.go
> +	err := db.Transaction(func(tx *gorm.DB) error {
これトランザクション取る必要ある？

2020-12-02 18:52 UTC, FujishigeTemma commented on model/games.go
> +// CheckGameIDs gameIDが全てあるか確認
```suggestion
// CheckGameIDs gameIDが登録済みのものに該当するか確認
```

2020-12-02 18:52 UTC, FujishigeTemma commented on model/games.go
> +	DontHaveVersionGameIDs []string
バージョンがないことってある？
→`POST /games`で初期バージョンも同時に投げるようにする(形式はsemver固定で)
https://godoc.org/golang.org/x/mod/semver

既存のやつでバージョンがないやつは`v1.0.0`かな？

2020-12-02 18:52 UTC, FujishigeTemma commented on model/games.go
> +
```suggestion
// InvalidGameIDs Checkをfailした理由ごとの不正なIDの配列
type InvalidGameIDs struct {
	NotFound  []string
	NoVersion []string
	NoAssets  []string
}

```

2020-12-02 18:52 UTC, FujishigeTemma commented on model/games.go
> +}
```suggestion
func (ids *InvalidGameIDs) Error() string {
	return fmt.Sprintf("invalid gameIds(not found:%s, no version: %s, no assets: %s)", strings.Join(ids.NotFound, "/"), strings.Join(ids.NoVersion, "/"), strings.Join(ids.NoAssets, "/"))
}
```

2020-12-02 18:52 UTC, FujishigeTemma commented on model/games.go
> +)
```suggestion
const (
	notFound gameIDState = iota
	noVersion
	noAsset
	ok
)
```

2020-12-02 18:52 UTC, FujishigeTemma commented on model/games.go
> +	gameIDMap := make(map[string]gameIDState, len(gameIDs))
```suggestion
	gameIDStateMap := make(map[string]gameIDState, len(gameIDs))
```

2020-12-02 18:52 UTC, FujishigeTemma commented on model/games.go
> +		gameIDMap[gameID] = notFound
```suggestion
		gameIDStateMap[gameID] = notFound
```

2020-12-02 18:52 UTC, FujishigeTemma commented on model/games.go
> +	}
```suggestion
	for rows.Next() {
		var gameID string
		var versionNum int
		var assetNum int
		err := rows.Scan(&gameID, &versionNum, &assetNum)
		if err != nil {
			return fmt.Errorf("failed to scan gameIDs: %w", err)
		}

		if versionNum == 0 {
			gameIDStateMap[gameID] = noVersion
			continue
		}
		if assetNum == 0 {
			gameIDStateMap[gameID] = noAssets
			continue
		}

		gameIDStateMap[gameID] = ok
	}
```

2020-12-02 18:52 UTC, FujishigeTemma commented on model/games.go
> +	return gameIDerr
```suggestion
	invalidGameIDs := &invalidGameIDs{}
	for gameID, state := range gameIDStateMap {
		switch state {
		case notFound:
			invalidGameIDs.NotFound = append(invalidGameIDs.NotFound, gameID)
		case noVersion:
			invalidGameIDs.NoVersion = append(invalidGameIDs.DontHaveVersionGameIDs, gameID)
		case noAssets:
			invalidGameIDs.NoAssets = append(invalidGameIDs.NoAssets, gameID)
		}
	}

	if len(invalidGameIDs.NotFound) > 0 || len(invalidGameIDs.NoVersion) > 0 || len(invalidGameIDs.NoAssets) > 0 {
		return invalidGameIDs
	}

	return nil
```

2020-12-02 18:52 UTC, FujishigeTemma commented on router/version.go
> +		}
```suggestion
		invalidIDs := &model.InvalidGameIDs{}
		if errors.As(err, invalidIDs) {
			return nil, invalidIDs
		}
```

2021-02-03 19:09 UTC, mazrean commented on model/game_version_relations.go
> +	err := db.Transaction(func(tx *gorm.DB) error {
当時の自分の考えの推測になるけど、ランチャーのバージョンが消されたときにinsertで外部キーでエラー吐いて死ぬと考えた&ロック取り忘れたのだと思う(論理削除だからいらないのでトランザクション取らないようにする)

2021-02-18 05:48 UTC, mazrean commented on model/game_version_relations.go
> +	err := db.Transaction(func(tx *gorm.DB) error {
トランザクション取らないようにした

2021-02-18 06:02 UTC, mazrean commented on model/games.go
> +	DontHaveVersionGameIDs []string
了解

2021-02-19 09:25 UTC, mazrean commented on model/games.go
> +	DontHaveVersionGameIDs []string
これは別PRでいいよね？

2021-05-13 02:57 UTC, FujishigeTemma requested changes

2021-05-13 02:57 UTC, FujishigeTemma commented on docs/schema.md
> +### seat_versions
width, heightって別のところにある？

2021-05-13 02:57 UTC, FujishigeTemma commented on docs/schema.md
> +| seat_id | int(11) | NO |  |  |  |  |
やっぱりいちいち`seat_id`から席の場所を算出するメリットなさそうだから位置(row, column)で持つようにして欲しい

2021-05-13 04:31 UTC, mazrean commented on docs/schema.md
> +| seat_id | int(11) | NO |  |  |  |  |
developに取り込まれているのがこっちに取り込まれていないだけです(pull --rebaseしてdevelop取り込みます)

2021-05-13 04:34 UTC, mazrean commented on docs/schema.md
> +### seat_versions
これもdevelopの変更が取り込まれていないだけ

2021-05-13 04:36 UTC, mazrean commented on docs/schema.md
> +| anke_to | text |  |  | NULL |  |  |
これ、別のブランチでやっていい？(変更がmodel内とかに波及して「POST /versions/:launcherVersionID/game実装」ではなくなるので)

2021-05-14 15:59 UTC, mazrean commented on docs/schema.md
> +| anke_to | text |  |  | NULL |  |  |
別PRで直した。
#111

2021-05-15 02:43 UTC, FujishigeTemma approved these changes

2021-05-18 07:50 UTC, merged