POST /games/:gameID/video実装
traPtitech/trap-collection-server pull request #75
Opened 2020-11-25 05:35 UTC by mazrean

実装した。
ファイルアップロードの仕様を変更したりしたので`add_post_game_image`をマージしている。

2020-11-25 10:54 UTC, FujishigeTemma requested changes

2020-11-25 10:54 UTC, FujishigeTemma commented on router/game.go
> +	log.Printf("debug: %s\n", fileName)
これ消し忘れ？

2020-11-25 10:54 UTC, FujishigeTemma commented on router/game.go
> +func (g *Game) postIntroduction(gameID string, introduction io.Reader, role string) error {
```suggestion
func (g *Game) postIntroduction(gameID string, introduction io.Reader, resourceType string) error {
```
roleではないと思う

2020-11-25 10:54 UTC, FujishigeTemma commented on model/game_introductions.go
> +	}
DBに依存しないバリデーション(拡張子)は一つ上で担保してあげるほうが良いと思う

2020-11-25 10:54 UTC, FujishigeTemma commented on router/game.go
> +func (g *Game) postIntroduction(gameID string, introduction io.Reader, role string) error {
Introductionがぼんやりしすぎてるので、ResourceFileとかにしたほうが良さそう。あとpostというよりはSaveとかの方がわかりやすい気がする。

2020-11-25 10:54 UTC, FujishigeTemma commented on router/game.go
> +
今の実装だと`/image`で動画も(`/video`で画像も)投稿できない？
それぞれ、今の`postIntroduction`にまとめずに別々で実装するか、Gameに紐づくファイルをまとめて扱うような切り方をするかのどっちかだと思うけど、まとめると責任が大きくなりすぎる気がするので、僕は別々のほうが良いと思う。

2020-11-25 12:34 UTC, mazrean commented on router/game.go
> +
拡張子のチェックするようにした

2020-11-25 12:34 UTC, mazrean commented on model/game_introductions.go
> +	}
router側でチェックするようにした

2020-11-25 12:35 UTC, mazrean commented on router/game.go
> +	log.Printf("debug: %s\n", fileName)
消し忘れなので消した(一応debugになっているのでproductionだと消えるけど)。

2020-11-27 16:09 UTC, FujishigeTemma commented on router/game.go
> +			isValidExt = true
breakしてると意図が伝わりやすい

2020-11-27 16:14 UTC, FujishigeTemma requested changes

2020-11-27 16:14 UTC, FujishigeTemma commented on router/game.go
> +}
gameのファイルのときだけ`get~`の関数があるの変じゃない？
imageもvideoも`getImageFileName`作って統一してほしい
あと、PRの責任範囲外のことをまとめてやるの減らしてほしい(or 名前変えてほしい)

2020-12-02 08:34 UTC, mazrean commented on router/game.go
> +}
一応新規追加ではなくてPostVideoとかを追加すると位置関係的にコードが読みづらいと思ったから位置を動かしただけではある(あとから関数1つの位置動かすだけのPR出してレビューしてもらうのもバカバカしいかと思ったので)。

2020-12-02 08:42 UTC, mazrean commented on router/game.go
> +}
追加した。

2020-12-02 08:43 UTC, mazrean commented on router/game.go
> +			isValidExt = true
直した

2020-12-02 17:11 UTC, FujishigeTemma approved these changes

2020-12-02 18:08 UTC, merged