GET /seats実装
traPtitech/trap-collection-server pull request #77
Opened 2020-12-01 08:19 UTC by mazrean

実装した。
実装するに当たって、コード生成でintとかの配列もポインタ型の配列になってしまう問題があったので修正している。

2020-12-01 14:43 UTC, FujishigeTemma commented on model/players.go
>  	}
これって認証？

2020-12-01 17:40 UTC, mazrean commented on model/players.go
>  	}
違う

2020-12-01 17:42 UTC, mazrean commented on model/players.go
>  	}
middlewareで認証済みだけど、productKeyが必要なのでDBを叩きに行っていて(contextに値持たせるほうがきれいなのはそうだけど)、DBがしんだりとかの何らかの理由でエラーが発生した場合に対応するためにこの部分はある

2020-12-02 17:20 UTC, FujishigeTemma commented on model/players.go
>  	}
`product_key`って元々何に使うやつだっけ？
なんでplayerが`product_key_id`に紐付いてるのかがわからんくなった。
> `access_tokenが使用済みかどうか`

もしかして`product_key`=`access_token`？

2020-12-02 18:28 UTC, mazrean commented on model/players.go
>  	}
確か今は`product_key=access_token`の実装になっているはずだけど、色々まずい…
現在、ランチャーはヘッダーにproduct_keyを入れてリクエストして、それがDBにあるproduct_keyならばとおして、なければ弾く実装になっている(usedというカラムの存在を完全に忘れていた…)。
なので、確か紙とかでの受け渡しで漏れる可能性の高いproduct_keyは最初に使われた時点で使えなくして、それ以降はproduct_keyと引き換えに発行したaccess_tokenでアクセスする、という形だったはずだけど、完全にその流れは崩壊してしまっている…(何なら、今見たらDBにaccess_tokenを記録するテーブルがないので、実装時点でこの流れを忘れていた可能性が高い)

2020-12-02 18:42 UTC, mazrean commented on model/players.go
>  	}
>実装時点でこの流れを忘れていた

のではなくて、たぶんproduct_keyと引き換えにsessionをつけたから大丈夫と思ってしまった(=access_tokenの役割をsessionで果たせると思ってしまった)のだと思う(`DBにあるproduct_keyならばとおして`の時点で今の実装ではsessionをランチャーにつけている)。

2020-12-05 14:11 UTC, FujishigeTemma requested changes
https://q.trap.jp/messages/3c6bb9e3-7de8-4338-82fd-1b64d840e18c

2021-02-03 13:16 UTC, closed without merging