席管理・ランチャーの権限管理修正(ファイル構造)
traPtitech/trap-collection-server pull request #81
Opened 2021-02-03 13:46 UTC by mazrean

#80 のAPIのグループの追加、テーブルの追加、カラムの変更とかの反映。実装はまだ。

2021-02-12 23:12 UTC, FujishigeTemma commented on model/access_tokens.go
> +}
AccessTokenの中にRefreshTokenが入ってるのどういう構造を考えてる？
どう使うつもりなのかよくわからんかった。

2021-02-12 23:12 UTC, FujishigeTemma commented on model/product_keys.go
>  // ProductKey アクセストークンの構造体
```suggestion
// ProductKey ProductKeyの構造体
```
typo?

2021-02-12 23:12 UTC, FujishigeTemma commented on model/product_keys.go
> -	Key               string `gorm:"type:varchar(29);NOT NULL;PRIMARY_KEY;default:\"\";"`
`varchar(29)`ってなんで？

2021-02-12 23:12 UTC, FujishigeTemma commented on model/seat_versions.go
> +}
これ本質的な情報持って無くない？

2021-02-18 05:03 UTC, mazrean commented on model/access_tokens.go
> +}
1. 管理者用UIからプロダクトキー発行(同時に複数個発行可能)
1. 販売時にプロダクトキーを渡す
1. ランチャーでプロダクトキーを用いてログインし、期限付きのアクセストークン取得
1. ランチャーはアクセストークンを用いてエンドポイントを叩く

でアクセストークンの有効期限が切れたあとに再取得で使うのとかを想定している(すぐに実装するつもりはない。ただ、このテーブルはtraQのOAuthのaccess tokenのテーブルを参考にして作っていて、traQのOAuthは再取得まだ実装されていないけどrefresh tokenのカラムがあったから新しくカラム追加するの面倒だから入れるとかかと思ったので同じ感じで入れている)。

2021-02-18 05:08 UTC, mazrean commented on model/product_keys.go
> -	Key               string `gorm:"type:varchar(29);NOT NULL;PRIMARY_KEY;default:\"\";"`
一応Appleのシリアルコードの形が英数字5文字×5のハイフン区切りらしいので、ユーザー入力の難易度とかを考えた結果そのぐらいになったのかと思ってtraP Collectionのシリアルコードもその形式にしようかと思っていた。
29は5× 5 + 4で29。

2021-02-18 05:08 UTC, mazrean commented on model/seat_versions.go
> +}
席のバージョンにバージョン名とか欲しい？

2021-02-19 19:20 UTC, FujishigeTemma commented on model/access_tokens.go
> +}
このPRで実装しないなら消してほしいのと、Access TokenとRefresh Tokenは多対一の関係だから別テーブルで持つほうが良いと思う(ので、構造体も後はならないはず)。

2021-02-19 19:23 UTC, FujishigeTemma commented on model/seat_versions.go
> +}
というより、肝心の席の状態に関する情報(そのバージョンでは席の配置がどうなってるかとか)がなさそうってこと

2021-02-24 15:38 UTC, mazrean commented on model/seat_versions.go
> +}
席の配置持たせるの？(というか、どういう形で持つのを想定している？)

2021-02-27 08:03 UTC, mazrean commented on model/access_tokens.go
> +}
消す。

2021-02-27 08:06 UTC, mazrean commented on model/access_tokens.go
> +}
消した。

2021-02-28 01:51 UTC, FujishigeTemma requested changes

2021-02-28 01:51 UTC, FujishigeTemma commented on model/access_tokens.go
> +	ExpiresIn   int          `gorm:"type:int(11);NOT NULL;"`
これ期間で持つより有効期限を直接持ったほうが良いと思ったんだけど期間を使うとこがあったりする？

2021-02-28 01:51 UTC, FujishigeTemma commented on model/access_tokens.go
> +	KeyID       string       `gorm:"type:varchar(36);NOT NULL;"`
product keyがIDに直接参照を持たないのって何か理由あったりする？

2021-02-28 01:51 UTC, FujishigeTemma commented on model/seat_versions.go
> +}
あれ、クライアントと席の対応って結局サーバーで持つんじゃなかったっけ(どっちにせよ、別テーブルになるからSeatVersionは書き換えなくないと言われればそうです。ちゃんと考えてなかった)

2021-05-05 05:22 UTC, mazrean commented on model/access_tokens.go
> +	ExpiresIn   int          `gorm:"type:int(11);NOT NULL;"`
有効期限の方が良いと思うので直します。

2021-05-05 05:46 UTC, mazrean commented on model/access_tokens.go
> +	KeyID       string       `gorm:"type:varchar(36);NOT NULL;"`
product keyがIDに直接参照を持つ、と言うのが、access tokenのidを要素にもつ、と言うことなら、product key一つに対してaccess tokenが複数存在するから。

2021-05-05 05:49 UTC, mazrean commented on model/seat_versions.go
> +}
席の番号と席の位置の対応関係はクライアントでいい感じにすると思っていたけど？

2021-05-05 05:50 UTC, mazrean commented on model/seat_versions.go
> +}
鯖で管理するならどう言うふうに席の位置関係の情報持って欲しいか教えて欲しい

2021-05-05 06:09 UTC, FujishigeTemma commented on model/access_tokens.go
> +	KeyID       string       `gorm:"type:varchar(36);NOT NULL;"`
何が聞きたかったか忘れた

2021-05-05 06:13 UTC, FujishigeTemma commented on model/seat_versions.go
> +}
クライアントで持つと同じ席を参照するクライアントがあったり、変更を２つのPCでしないといけなくなったりして面倒そう

`バージョン - 席ID - クライアントID`で良さそう

2021-05-05 06:17 UTC, mazrean commented on model/seat_versions.go
> +}
`クライアントID`は何のこと言っている？(ランチャーのIDのことなら`ランチャー - バージョン - 席ID`にすでになっているよ？)

2021-05-05 06:19 UTC, mazrean commented on model/seat_versions.go
> +}
> 席の番号と席の位置の対応関係はクライアントでいい感じにすると思っていたけど？

これのクライアントはWebクライアントのことを指していて、席の位置は教室の中で素席がどこにあるか、みたいなののことを言っている

2021-05-12 06:12 UTC, FujishigeTemma requested changes

2021-05-12 06:12 UTC, FujishigeTemma commented on docs/schema.md
> +| expires_in | datetime | NO |  |  |  |  |
```suggestion
| expires_at | datetime | NO |  |  |  |  |
```

2021-05-12 06:12 UTC, FujishigeTemma commented on model/seat_versions.go
> +}
traQで話した内容が反映されてなさそう

2021-05-12 07:43 UTC, FujishigeTemma commented
:LGTM:

2021-05-12 07:43 UTC, FujishigeTemma approved these changes

2021-05-12 07:44 UTC, merged