versionID wo
traPtitech/trap-collection-server pull request #92
Opened 2021-05-12 14:10 UTC by mazrean

2021-05-13 01:11 UTC, FujishigeTemma requested changes
なんでバレるとだめなのかよくわかんなかったけど変更は良さそう

2021-05-13 01:11 UTC, FujishigeTemma commented on docs/swagger/openapi.yml
> +        example: "91f8feff-4293-468f-97fb-3c5b7726f815"
https://swagger.io/docs/specification/data-models/data-types/

2021-05-14 15:06 UTC, mazrean commented
明らかにまずいは嘘

2021-05-14 15:10 UTC, mazrean commented
理由としては
- idでauto incrementとuuidのどちらかに統一したい
- 何らかの理由で認証通り抜けられたときに、エンドポイントに含まれるversion idがuuidの方がリスクが若干減る
- game id推測されるのもあまりうれしくはない(認証突破されなければ問題ないけど)のでどっちにしろ統一するのはuuid

というのがある

2021-05-15 02:42 UTC, FujishigeTemma commented
schema指定したらexample自動でついてくる気がする

2021-05-18 09:16 UTC, FujishigeTemma commented on docs/swagger/openapi.yml
> +          example: "91f8feff-4293-468f-97fb-3c5b7726f815"
formatの間違い？

2021-05-21 07:08 UTC, FujishigeTemma approved these changes

2021-05-29 07:17 UTC, merged